apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jordannlewis-com-tls
spec:
  secretName: jordannlewis-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jordannlewis.com
  dnsNames:
    - jordannlewis.com
    - www.jordannlewis.com
