name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t jordanlewis9/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true jordanlewis9/react-test npm test

      - run: docker build -t jordanlewis9/multi-client-multi-docker ./client
      - run: docker build -t jordanlewis9/multi-nginx-multi-docker ./nginx
      - run: docker build -t jordanlewis9/multi-server-multi-docker ./server
      - run: docker build -t jordanlewis9/multi-worker-multi-docker ./worker

      - run: docker push jordanlewis9/multi-client-multi-docker
      - run: docker push jordanlewis9/multi-nginx-multi-docker
      - run: docker push jordanlewis9/multi-server-multi-docker
      - run: docker push jordanlewis9/multi-worker-multi-docker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-2-634610692536
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip